// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friends.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :exec
UPDATE friendships
SET status = 'accepted', updated_at = NOW()
WHERE user_id = $2 AND friend_id = $1 AND status = 'pending'
`

type AcceptFriendRequestParams struct {
	FriendID uuid.UUID `json:"friend_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) error {
	_, err := q.db.ExecContext(ctx, acceptFriendRequest, arg.FriendID, arg.UserID)
	return err
}

const areFriends = `-- name: AreFriends :one
SELECT EXISTS(
    SELECT 1 FROM friendships
    WHERE ((user_id = $1 AND friend_id = $2) OR (user_id = $2 AND friend_id = $1))
      AND status = 'accepted'
) as are_friends
`

type AreFriendsParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

func (q *Queries) AreFriends(ctx context.Context, arg AreFriendsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, areFriends, arg.UserID, arg.FriendID)
	var are_friends bool
	err := row.Scan(&are_friends)
	return are_friends, err
}

const blockUser = `-- name: BlockUser :exec
INSERT INTO friendships (user_id, friend_id, status)
VALUES ($1, $2, 'blocked')
ON CONFLICT (user_id, friend_id)
DO UPDATE SET status = 'blocked', updated_at = NOW()
`

type BlockUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.ExecContext(ctx, blockUser, arg.UserID, arg.FriendID)
	return err
}

const createFriendRequest = `-- name: CreateFriendRequest :one
INSERT INTO friendships (user_id, friend_id, status)
VALUES ($1, $2, 'pending')
RETURNING id, user_id, friend_id, status, created_at, updated_at
`

type CreateFriendRequestParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, createFriendRequest, arg.UserID, arg.FriendID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFriendFeed = `-- name: GetFriendFeed :many
SELECT c.id, c.created_at, c.updated_at, c.body, c.user_id, u.email as author_email
FROM chirps c
INNER JOIN users u ON c.user_id = u.id
WHERE c.user_id IN (
    SELECT 
        CASE 
            WHEN f.user_id = $1 THEN f.friend_id
            ELSE f.user_id
        END
    FROM friendships f
    WHERE (f.user_id = $1 OR f.friend_id = $1)
      AND f.status = 'accepted'
)
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFriendFeedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetFriendFeedRow struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Body        string    `json:"body"`
	UserID      uuid.UUID `json:"user_id"`
	AuthorEmail string    `json:"author_email"`
}

func (q *Queries) GetFriendFeed(ctx context.Context, arg GetFriendFeedParams) ([]GetFriendFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriendFeed, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendFeedRow
	for rows.Next() {
		var i GetFriendFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
			&i.AuthorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriends = `-- name: GetFriends :many
SELECT 
    CASE 
        WHEN f.user_id = $1 THEN f.friend_id
        ELSE f.user_id
    END as friend_id,
    u.email,
    u.created_at,
    f.created_at as friends_since
FROM friendships f
INNER JOIN users u ON (
    CASE 
        WHEN f.user_id = $1 THEN f.friend_id = u.id
        ELSE f.user_id = u.id
    END
)
WHERE (f.user_id = $1 OR f.friend_id = $1)
  AND f.status = 'accepted'
ORDER BY f.created_at DESC
`

type GetFriendsRow struct {
	FriendID     interface{} `json:"friend_id"`
	Email        string      `json:"email"`
	CreatedAt    time.Time   `json:"created_at"`
	FriendsSince time.Time   `json:"friends_since"`
}

func (q *Queries) GetFriends(ctx context.Context, userID uuid.UUID) ([]GetFriendsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendsRow
	for rows.Next() {
		var i GetFriendsRow
		if err := rows.Scan(
			&i.FriendID,
			&i.Email,
			&i.CreatedAt,
			&i.FriendsSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendshipStatus = `-- name: GetFriendshipStatus :one
SELECT status FROM friendships
WHERE (user_id = $1 AND friend_id = $2) OR (user_id = $2 AND friend_id = $1)
ORDER BY updated_at DESC
LIMIT 1
`

type GetFriendshipStatusParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

func (q *Queries) GetFriendshipStatus(ctx context.Context, arg GetFriendshipStatusParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getFriendshipStatus, arg.UserID, arg.FriendID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getPendingRequests = `-- name: GetPendingRequests :many
SELECT u.id, u.email, u.created_at, f.created_at as requested_at
FROM friendships f
INNER JOIN users u ON f.user_id = u.id
WHERE f.friend_id = $1 AND f.status = 'pending'
ORDER BY f.created_at DESC
`

type GetPendingRequestsRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	CreatedAt   time.Time `json:"created_at"`
	RequestedAt time.Time `json:"requested_at"`
}

func (q *Queries) GetPendingRequests(ctx context.Context, friendID uuid.UUID) ([]GetPendingRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingRequests, friendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingRequestsRow
	for rows.Next() {
		var i GetPendingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.CreatedAt,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSentRequests = `-- name: GetSentRequests :many
SELECT u.id, u.email, u.created_at, f.created_at as requested_at
FROM friendships f
INNER JOIN users u ON f.friend_id = u.id
WHERE f.user_id = $1 AND f.status = 'pending'
ORDER BY f.created_at DESC
`

type GetSentRequestsRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	CreatedAt   time.Time `json:"created_at"`
	RequestedAt time.Time `json:"requested_at"`
}

func (q *Queries) GetSentRequests(ctx context.Context, userID uuid.UUID) ([]GetSentRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSentRequests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSentRequestsRow
	for rows.Next() {
		var i GetSentRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.CreatedAt,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectFriendRequest = `-- name: RejectFriendRequest :exec
UPDATE friendships
SET status = 'rejected', updated_at = NOW()
WHERE user_id = $2 AND friend_id = $1 AND status = 'pending'
`

type RejectFriendRequestParams struct {
	FriendID uuid.UUID `json:"friend_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) RejectFriendRequest(ctx context.Context, arg RejectFriendRequestParams) error {
	_, err := q.db.ExecContext(ctx, rejectFriendRequest, arg.FriendID, arg.UserID)
	return err
}

const removeFriendship = `-- name: RemoveFriendship :exec
DELETE FROM friendships
WHERE (user_id = $1 AND friend_id = $2) OR (user_id = $2 AND friend_id = $1)
`

type RemoveFriendshipParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

func (q *Queries) RemoveFriendship(ctx context.Context, arg RemoveFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, removeFriendship, arg.UserID, arg.FriendID)
	return err
}
